services:
  flask_app:
    build: .
    user: "1000:1000"
    ports:
      - "5000:5000"
    environment:
      - XDG_CACHE_HOME=/tmp/.cache
    env_file:
      - .env
    volumes:
      - type: bind
        source: /mnt/ceph-videos/YouTube
        target: /mnt/ceph-videos/YouTube
      - type: bind
        source: /home/wassu/jellyfin-downloader/download-archive.txt
        target: /app/download-archive.txt
    restart:
      unless-stopped
